### ISSUE TITLE
Zadania w tym tygodniu

### ISSUE THREAD

**Issue by CudnyBrzydal** [radoslawmikolajczyk/INPG_Project#63]
Dodałem część zadań na ten tydzień. Zapewne w czwartek, bądź piątek dodam więcej. Proszę o wasze komentarze co uważacie o ich ilości (bym nie przydzielił za dużo).

**Comment by radoslawmikolajczyk** [comment]
Wg mnie jest spoko

**Comment by Katarzynainpg** [comment]
jest okej
