### ISSUE TITLE
Juz zrobiony backlog, Mozesz zarzadzac tym, tylko tak rob zebysmy mieli co robic przez 3 tyg.

### ISSUE THREAD

**Issue by radoslawmikolajczyk** [radoslawmikolajczyk/INPG_Project#96]

**Comment by SzymonINPG** [comment]
Dzięki za pomoc, rozdzieliłem po jednym zadaniu dla każdego, jeżeli później zacznie brakować zadań to zaczniemy robić "optymalizację" kodu albo np. zmianę oprawy graficznej
